In [8]:
import keras

Using TensorFlow backend.


In [9]:
from keras.models import Sequential

In [10]:
model = Sequential()

In [11]:
from keras.layers import Dense

In [12]:
from keras.applications import VGG16

In [13]:
from keras.layers import merge,Input

In [14]:
#loading image
import cv2

In [28]:
image = cv2.imread('shoe.jpg',1)
dog = cv2.imread('dog.jpg',1)

In [16]:
print(image.shape)

(224, 224, 3)


In [17]:
resized = cv2.resize(image, (224,224))

In [18]:
from matplotlib import pyplot as plt

In [19]:
image_input = Input(shape=(224,224,3))

In [50]:
model = VGG16(input_tensor = image_input)

In [51]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [22]:
last_layer = model.get_layer('fc2').output

In [23]:
lstm_input = Input(shape=(4096,50))

In [24]:
LSTM1 = keras.layers.LSTM(1,name= 'LSTM1')(lstm_input)

In [25]:
final_dense = keras.layers.Dense(1)(LSTM1)

In [58]:
model.layers.pop()

In [76]:
model.outputs = [model.layers[-1].output]
model.output_layers = [model.layers[-1]] # added this line in addition to zo7 solution
model.layers[-1].outbound_nodes = []

In [77]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [173]:
dog = dog.reshape(224,224,3)

In [171]:
shoe = image.reshape(224, 224, 3)

In [177]:
x1_batch = [0,0]

x1_batch[0] = dog
x1_batch[1] = shoe

x1_batch = np.array(x1_batch)
 


In [178]:
x1_batch.shape

(2, 224, 224, 3)

In [179]:
activations = model1.predict(x1_batch)

In [181]:
activations

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  7.34299946,
         0.        ,  7.18407965]], dtype=float32)

In [91]:
activations.shape

(1, 4096)

In [85]:
from keras.models import Model

In [87]:
model1 = Model(inputs=model.input, outputs=model.get_layer('fc1').output)

In [88]:
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [130]:
###LSTM
import numpy as np
#x_train = np.random.random_sample((5,5,4096))
y_train = np.random.random_sample((5,))
#x_test = np.random.random_sample((2,5,4096))
y_test = np.random.random_sample((3,1))

In [123]:
x = []

for i in range(0,8):
    fc = []
    for j in range(0,5):
        fc1 = np.random.random_sample(4096)
        fc.append(fc1)
    x.append(fc)
    

x = np.array(x)
print(x)
    
        

[[[ 0.56718277  0.58951102  0.64089215 ...,  0.04317081  0.60846357
    0.24979715]
  [ 0.89925944  0.70085782  0.94367782 ...,  0.20395351  0.61435237
    0.44238703]
  [ 0.50649155  0.07004559  0.3680923  ...,  0.47253513  0.41637347
    0.21182494]
  [ 0.44972061  0.97414113  0.5414787  ...,  0.95962967  0.39361163
    0.18766256]
  [ 0.05016576  0.34254382  0.59390823 ...,  0.67113049  0.51018367
    0.91974118]]

 [[ 0.44502288  0.99696573  0.35791812 ...,  0.41061944  0.2497252
    0.86496208]
  [ 0.00981849  0.16547435  0.38363211 ...,  0.30445062  0.50648166
    0.73293864]
  [ 0.90746627  0.40979506  0.11165562 ...,  0.9211089   0.23891881
    0.72976323]
  [ 0.63234502  0.78893511  0.99227446 ...,  0.88615359  0.48740267
    0.14587193]
  [ 0.6015948   0.14937684  0.49888655 ...,  0.63552443  0.39208983
    0.63127315]]

 [[ 0.84473409  0.66836463  0.81378465 ...,  0.61493472  0.41939143
    0.04682985]
  [ 0.5118312   0.35883398  0.61825814 ...,  0.10144195  0.46073467
    0

In [124]:
x_train = x[:-3]

In [125]:
x_test = x[5:]

In [126]:
x_test

array([[[ 0.98591582,  0.04427887,  0.09985804, ...,  0.72971098,
          0.98219777,  0.4266246 ],
        [ 0.95806341,  0.09347391,  0.84244002, ...,  0.78522383,
          0.84966118,  0.55238042],
        [ 0.50891772,  0.91406738,  0.52989445, ...,  0.39203691,
          0.39848008,  0.98623555],
        [ 0.69331293,  0.29515792,  0.85100091, ...,  0.58274252,
          0.61897111,  0.95084283],
        [ 0.52432784,  0.78793786,  0.80675779, ...,  0.09011492,
          0.9915543 ,  0.69704052]],

       [[ 0.728636  ,  0.06171532,  0.9795118 , ...,  0.2424868 ,
          0.44282267,  0.11434247],
        [ 0.46962133,  0.80585771,  0.81234245, ...,  0.05927138,
          0.9660297 ,  0.92967395],
        [ 0.87321059,  0.59503545,  0.04822864, ...,  0.8836942 ,
          0.75098338,  0.1622094 ],
        [ 0.05071064,  0.60695113,  0.22969363, ...,  0.23304902,
          0.24291863,  0.1704673 ],
        [ 0.68943991,  0.036329  ,  0.5121377 , ...,  0.09731503,
          0.33

In [133]:
#LSTM
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.datasets import imdb
from keras.callbacks import EarlyStopping
import numpy as np

print('Build model...')
model = Sequential()
model.add(LSTM(64, dropout=0.0, recurrent_dropout=0.0,input_shape=(None,4096)))
model.add(Dense(32))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
print('Train...')

model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=10)
print('one epoch completed')

Build model...
Train...
Train on 5 samples, validate on 3 samples
Epoch 1/10
1s - loss: 0.1868 - val_loss: 18.1744
Epoch 2/10
0s - loss: 19.0604 - val_loss: 7.0037
Epoch 3/10
0s - loss: 7.4747 - val_loss: 1.0824
Epoch 4/10
0s - loss: 1.3017 - val_loss: 0.0134
Epoch 5/10
0s - loss: 0.1047 - val_loss: 0.0258
Epoch 6/10
0s - loss: 0.0808 - val_loss: 0.0412
Epoch 7/10
0s - loss: 0.0824 - val_loss: 0.0577
Epoch 8/10
0s - loss: 0.0873 - val_loss: 0.0742
Epoch 9/10
0s - loss: 0.0940 - val_loss: 0.0882
Epoch 10/10
0s - loss: 0.1002 - val_loss: 0.0947
Epoch 00009: early stopping
one epoch completed


In [145]:
model.predict(x_test)

array([[ 0.15390524],
       [ 0.15858486],
       [ 0.15141788]], dtype=float32)

In [15]:
#Playing with resnet
from keras.applications import ResNet50

In [17]:
resnet = ResNet50(input_tensor = image_input)

102703104/102853048 [============================>.] - ETA: 0s

In [18]:
resnet.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_1 (InputLayer)             (None, 224, 224, 3)   0                                            
____________________________________________________________________________________________________
zero_padding2d_1 (ZeroPadding2D) (None, 230, 230, 3)   0           input_1[0][0]                    
____________________________________________________________________________________________________
conv1 (Conv2D)                   (None, 112, 112, 64)  9472        zero_padding2d_1[0][0]           
____________________________________________________________________________________________________
bn_conv1 (BatchNormalization)    (None, 112, 112, 64)  256         conv1[0][0]                      
___________________________________________________________________________________________

In [ ]:
resnet.layers.pop()